In [19]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sb

In [20]:
data = pd.read_csv('smartwatches.csv', index_col=[0])
data.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,NaN,NaN,NaN,NaN,8.0,Yes,NaN,35 - 50 g
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,NaN,NaN,Silicon,Yes,3.5,Yes,1.8 inches,50 - 75 g
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,NaN,NaN,Silicon,Yes,8.0,Yes,1.7 inches,35 - 50 g
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,NaN,NaN,Silicon,Yes,3.5,Yes,1.8 inches,75g +
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,NaN,NaN,Other,Yes,8.0,Yes,1.7 inches,35 - 50 g

In [21]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                450 non-null    str
 1   Current Price        440 non-null    float64
 2   Original Price       377 non-null    float64
 3   Discount Percentage  377 non-null    float64
 4   Rating               444 non-null    float64
 5   Number OF Ratings    391 non-null    float64
 6   Model Name           415 non-null    str
 7   Dial Shape           327 non-null    str
 8   Strap Color          327 non-null    str
 9   Strap Material       381 non-null    str
 10  Touchscreen          413 non-null    str
 11  Battery Life (Days)  418 non-null    float64
 12  Bluetooth            444 non-null    str
 13  Display Size         420 non-null    str
 14  Weight               264 non-null    str
dtypes: float64(6), str(9)
memory usage: 52.9 KB

In [23]:
data.describe()

,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Battery Life (Days),Display Size
count,440.000000,377.000000,377.000000,444.000000,391.000000,418.000000,420.000000
mean,12747.554545,14598.204244,48.236894,4.031306,11594.726343,14.077392,2.171190
std,17760.666099,15450.028869,24.109830,0.550548,40423.889227,7.718503,4.381144
min,1199.000000,1669.000000,-79.688436,1.000000,1.000000,0.750000,0.000000
25%,2180.750000,5999.000000,33.337037,3.900000,68.500000,8.000000,1.300000
50%,3999.000000,7999.000000,54.550414,4.100000,996.000000,17.500000,1.600000
75%,17121.750000,17999.000000,66.677780,4.300000,6022.000000,22.000000,1.800000
max,139990.000000,96390.000000,91.004550,5.000000,619130.000000,22.000000,45.000000

In [33]:
pd.DataFrame({
    'Columns': data.columns,
    'Missing_values': [data[i].isna().sum() for i in data.columns],
    'duplicate_values': [data[i].duplicated().sum() for i in data.columns]
    
})

                Columns  Missing_values  duplicate_values
0                 Brand               0               432
1         Current Price              10               285
2        Original Price              73               345
3   Discount Percentage              73               178
4                Rating               6               422
5     Number OF Ratings              59               199
6            Model Name              35                60
7            Dial Shape             123               443
8           Strap Color             123               419
9        Strap Material              69               434
10          Touchscreen              37               447
11  Battery Life (Days)              32               442
12            Bluetooth               6               447
13         Display Size              30               409
14               Weight             186               444

In [22]:
# Change dtype of Display size

data.loc[:, "Display Size"] = data.loc[:,'Display Size'].str.strip('inches')
data['Display Size'] = data['Display Size'].astype('float')

In [34]:
# Imputing missing values on a Categorical col. based on most freq val in their respective Brand in each col.

categorical_mode = data.groupby('Brand')[
    data.select_dtypes(include='object') # select all col with dtype object
    .columns.drop(['Brand']) # excluding Brand
    ].agg(lambda x:x.mode().iloc[0] if not x.mode().empty else np.nan) # Impute a mode in each col

categorical_mode

C:\Users\bhave\AppData\Local\Temp\ipykernel_26104\421939513.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.select_dtypes(include='object') # select all col with dtype object

,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Bluetooth,Weight
Brand,,,,,,,
amazfit,Bip 3 Pro with 1.69 inch Large Color Display B...,Circle,Black,Silicon,Yes,Yes,<= 20 g
ambrane,FitShot Curl,Square,Black,Silicon,Yes,Yes,35 - 50 g
apple,Apple Watch SE,Rectangle,Black,Silicon,Yes,Yes,<= 20 g
boat,Watch Flash,Rectangle,Black,Silicon,Yes,Yes,35 - 50 g
crossbeats,S4 Max,NaN,NaN,NaN,Yes,Yes,20 - 35 g
dizo,D TALK SMART WATCH (SILVER GREY),Rectangle,Black,Silicon,Yes,Yes,20 - 35 g
fire-boltt,beast pro,Square,Black,Silicon,Yes,Yes,75g +
fitbit,Blaze,Square,Black,Silicon,Yes,Yes,20 - 35 g
fossil,4th Gen Explorist HR,Circle,Black,Stainless Steel,Yes,Yes,75g +
garmin,7.54E+11,Circle,Black,Silicon,Yes,Yes,20 - 35 g
gizmore,910,Square,Black,Silicon,Yes,Yes,75g +
hammer,NaN,NaN,NaN,NaN,NaN,Yes,75g +
honor,ARG-B39-cr,Circle,Black,Leather,Yes,Yes,20 - 35 g
huawei,Fit,Circle,Black,Silicon,Yes,Yes,75g +
noise,"Caliber Buzz Advanced BT Calling(True Sync), 1...",Rectangle,Black,Other,Yes,Yes,35 - 50 g
pebble,Aspire Unisex 2.5D Curved Screen Smartwatch wi...,Square,Black,Silicon,Yes,Yes,20 - 35 g
samsung,Galaxy Watch 3 41 mm,Circle,Black,Fluoroelastomer,Yes,Yes,20 - 35 g
zebronics,FIT380CH,Square,Black,Silicon,Yes,Yes,75g +

In [35]:
# Imputing missing values on Numerical col.

numerical_median = data.groupby('Brand')[
    data.select_dtypes(include = np.number)
    .columns].median()

numerical_median

,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Battery Life (Days),Display Size
Brand,,,,,,,
amazfit,8249.0,15999.0,29.585441,4.15,575.0,8.00,1.40
ambrane,1799.0,4999.0,60.542248,4.20,2475.0,22.00,1.70
apple,41900.0,31400.0,1.570780,4.60,2847.0,22.00,1.60
boat,1999.0,6990.0,74.263233,4.00,19590.0,22.00,1.70
crossbeats,3999.0,10999.0,63.338111,4.10,2426.0,5.80,1.85
dizo,2749.0,5999.0,47.510002,4.10,663.0,22.00,1.80
fire-boltt,3299.0,9999.0,65.006501,3.70,2571.0,22.00,1.45
fitbit,18849.0,22249.0,15.348749,4.60,396.5,10.50,1.30
fossil,14995.0,21995.0,39.405881,4.00,112.5,17.50,1.30
garmin,39490.0,44990.0,15.193720,4.60,19.0,17.50,1.20
gizmore,1999.0,5999.0,69.000009,4.00,69.5,5.75,1.60
hammer,1799.0,4999.0,64.012803,3.60,516.0,NaN,1.80
honor,10023.0,14999.0,26.505356,4.30,1445.0,12.50,1.40
huawei,14990.0,20990.0,40.020010,4.40,196.0,8.00,1.40
noise,1799.0,5999.0,64.012803,4.10,13901.0,8.00,1.70
pebble,3999.0,6999.0,43.563340,4.00,1176.0,12.50,1.10
samsung,24490.0,33999.0,18.609735,4.30,567.0,3.50,1.40
zebronics,2624.0,5999.0,56.011202,3.90,77.5,22.00,3.30

In [ ]:
obj = 0
no = 0

for col in data.columns.drop('Brand'):
    if data[col].dtype == '0':
        data[col] = data[col].fillna(data['Brand'].map(categorical_mode[col]))
        obj+=1

    elif np.issubdtype(data[col].dtype, np.number):
        data[col] = data[col].fillna(data['Brand'].map(numerical_median[col]))
        no += 1